# Generated by Django 3.2 on 2021-11-26 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City_master',
            fields=[
                ('city_id', models.IntegerField(default=None, max_length=5, primary_key=True, serialize=False)),
                ('city', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='State_master',
            fields=[
                ('state_id', models.IntegerField(default=None, max_length=5, primary_key=True, serialize=False)),
                ('state', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student_master',
            fields=[
                ('student_id', models.IntegerField(default=None, max_length=5, primary_key=True, serialize=False)),
                ('student_f_name', models.CharField(default=None, max_length=20)),
                ('student_m_name', models.CharField(default=None, max_length=20)),
                ('student_l_name', models.CharField(default=None, max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.city_master')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.state_master')),
            ],
        ),
    ]
